### ISSUE TITLE
Refactor Into a pip installable package

### ISSUE THREAD

**Issue by colonelpanic8** [muneebalam/Hockey#1]
Is this a change that you would be open to?

I think it would be cool to do this, but it would involve restructuring the directory hierarchy and renaming the files etc.

**Comment by muneebalam** [comment]
Yes, I'd like to do it. On the summer to-do list.

**Comment by muneebalam** [comment]
I've started this in a new project, [scrapenhl2](https://github.com/muneebalam/scrapenhl2)
